# Description
# 中文
# English
# Given two strings s and t which consist of only lowercase letters.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Find the letter that was added in t.

# Have you met this question in a real interview?  
# Example
# Example：

# Input：s = "abcd"，t = "abcde"
# Output：'e'
# Explanation：'e' is the letter that was added.

class Solution:
    """
    @param s: a string
    @param t: a string
    @return: the letter that was added in t
    """
    def findTheDifference(self, s, t):
        # Write your code here
        s = sorted(s)
        t = sorted(t)
        print(s,t)
        for i in range(len(s)):
            if s[i] != t[i]:
                return t[i]
        return t[-1]
        
        
        #  flag = 0
        # for i in range(len(s)):
        #     # 计算每一位字符的Ascll码之差
        #     flag += (ord(t[i]) - ord(s[i]))
        # flag += ord(t[-1])
        # return chr(flag)